# Site settings
title: "Silver W0o0W"
email: silver.codingcat@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: ""
title_description: "Wel wel welcome Silver's com"
title_image: "/resource/avatar.png"
google_analytics: "UA-20365477-4"
disqus_account: none
github_repository: https://github.com/SilverW0o0W/Blog
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: SilverW0o0W
github_username:  SilverW0o0W
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/SilverW0o0W\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

theme: jekyll-theme-cayman
